### ISSUE TITLE
Add logos to the interface

### ISSUE THREAD

**Issue by olejandro** [tokni/shift#4]

**Comment by olejandro** [comment]
@olavurellefsen, we need logos of the project partners on shift.tokni.com

**Comment by rafsdtu** [comment]
![Shift_Title+Subtitle_Colour](https://user-images.githubusercontent.com/48917523/63577830-8c848100-c58f-11e9-8c3a-3ee3fe366244.png)
![NER-Logotype-blue-Large-2270x570](https://user-images.githubusercontent.com/48917523/63577835-8ee6db00-c58f-11e9-8fa2-6109622a349f.png)
![NER-Logotype-blue-Medium-1135x285](https://user-images.githubusercontent.com/48917523/63577838-90180800-c58f-11e9-8500-9405c4e0a7e8.png)
[Shift_logos_partners.pptx](https://github.com/tokni/shift/files/3533505/Shift_logos_partners.pptx)

**Comment by olavurellefsen** [comment]
Fixed in #7
