### ISSUE TITLE
Add SHIFT project description to the interface

### ISSUE THREAD

**Issue by rafsdtu** [tokni/shift#6]
@olavurellefsen, we would like to include the SHIFT project description on shift.tokni.com. The description includes also partners and the links to their webpages.

**Comment by rafsdtu** [comment]
[Short description Shift_for TimesNordic Webinterface.docx](https://github.com/tokni/shift/files/3534233/Short.description.Shift_for.TimesNordic.Webinterface.docx)

**Comment by olavurellefsen** [comment]
Fixed in #8
